export const industries = [
    "Retail & E-commerce",
    "Fintech & Financial Services",
    "Manufacturing & Industrial",
    "Logistics & Transportation",
    "Consulting & Professional Services",
    "Hospitality & Tourism",
    "Technology & Software",
    "Healthcare & Pharmaceuticals",
    "Real Estate & Construction",
    "Agriculture & Agribusiness",
    "Media & Entertainment",
    "Education & EdTech",
    "Oil & Gas / Energy",
    "Telecommunications",
    "Automotive & Mobility",
    "Food & Beverage",
    "Sports & Recreation",
    "Legal & Compliance Services",
    "Marketing & Advertising",
    "Other (Specify)",
  ];