export const bankList: BankName[] = [
    "Bank Names",
    "3line Card Management Limited",
    "9Payment Service Bank",
    "AAA Finance",
    "AB Microfinance Bank",
    "Abbey Mortgage Bank",
    "Above Only Microfinance Bank",
    "ABU Microfinance Bank",
    "Abulesoro Microfinance Bank",
    "Accelerex Network Limited",
    "Access Bank",
    "Access Yello",
    "AccessMobile",
    "Accion Microfinance Bank",
    "Ada Microfinance Bank",
    "Addosser Microfinance Bank",
    "Adeyemi College Staff Microfinance Bank",
    "Advans La Fayette Microfinance Bank",
    "Afekhafe Microfinance Bank",
    "Afemai Microfinance Bank",
    "AG Mortgage Bank",
    "Akpo Microfinance Bank",
    "Aku Microfinance Bank",
    "Akuchuckwu Microfinance Bank",
    "Akwa Savings & Loans Limited",
    "AL-Barakah Microfinance Bank",
    "Alekun Microfinance Bank",
    "Alert Microfinance Bank",
    "Al-Hayat Microfinance Bank",
    "Allworkers Microfinance Bank",
    "Ally Microfinance Bank",
    "Alpha Kapital Microfinance Bank",
    "Alvana Microfinance Bank",
    "Amac Microfinance Bank",
    "Amju Unique Microfinance Bank",
    "AMML MFB",
    "Amoye Microfinance Bank",
    "Ampersand Microfinance Bank",
    "Anchorage Microfinance Bank",
    "Aniocha Microfinance bank",
    "Apeks Microfinance Bank",
    "Apple Microfinance Bank",
    "Aramoko Microfinance Bank",
    "Arise Microfinance Bank",
    "ASOSavings & Loans",
    "Aspire Microfinance Bank",
    "AssetMatrix Microfinance Bank",
    "Assets Microfinance Bank",
    "Astrapolaris Microfinance Bank",
    "Auchi Microfinance Bank",
    "Ave Maria Microfinance Bank",
    "Aztec Microfinance Bank",
    "Baines Credit Microfinance Bank",
    "Balera Microfinance Bank",
    "Balogun Fulani Microfinance Bank",
    "Balogun Gambari Microfinance Bank",
    "Banc Corp MFB",
    "BC Kash Microfinance Bank",
    "Beststar MFB",
    "BIPC Microfinance Bank",
    "BishopGate Microfinance Bank",
    "BluePrint Investments Microfinance Bank",
    "Boctrust Microfinance Bank",
    "BOI Microfinance Bank",
    "Boji MFB",
    "Borgu Microfinance Bank",
    "Bosak Microfinance Bank",
    "Bowen Microfinance Bank",
    "Branch International Financial Services",
    "Brent Mortgage Bank",
    "Brethren Microfinance Bank",
    "Bridgeway Microfinance Bank",
    "Brightway Microfinance Bank",
    "Broadview Microfinance Bank",
    "Business Support Microfinance Bank",
    "Caretaker Microfinance Bank",
    "CashConnect Microfinance Bank",
    "Cedar Microfinance Bank",
    "Cellulant",
    "CEMCS Microfinance Bank",
    "Central Bank of Nigeria",
    "Changan RTS Microfinance Bank",
    "Chase Microfinance Bank",
    "Chikum Microfinance Bank",
    "Chukwunenye MFB",
    "Cintrust Microfinance Bank",
    "CIT Microfinance Bank",
    "Citi Bank",
    "Coalcamp Microfinance Bank",
    "Coastline Microfinance Bank",
    "Confidence MFB",
    "Conpro Microfinance Bank",
    "Consistent Trust Microfinance Bank",
    "Consumer Microfinance Bank",
    "Contec Global Infotech Limited (NowNow)",
    "Coop Mortgage Bank",
    "Corestep Microfinance Bank",
    "Coronation Merchant Bank",
    "Covenant MFB",
    "Credit Afrique Microfinance Bank",
    "Creditville MFB",
    "Crescent Microfinance Bank",
    "Crowdforce",
    "Cyberspace Limited",
    "Davodani Microfinance Bank",
    "Daylight Microfinance Bank",
    "Delta Trust Microfinance Bank",
    "Diamond Bank",
    "Dignity Finance",
    "Eagle Flight Microfinance Bank",
    "Eartholeum",
    "e-Barcs Microfinance Bank",
    "Ecobank Bank",
    "Ecobank Xpress Account",
    "EcoMobile",
    "EdFin Microfinance Bank",
    "Egwafin Microfinance Bank",
    "Ekondo MFB",
    "EK-Reliable Microfinance Bank",
    "Emeralds Microfinance Bank",
    "Empire trust MFB",
    "eNaira",
    "Enco Finance",
    "Enrich Microfinance Bank",
    "Enterprise Bank",
    "Esan Microfinance Bank",
    "Eso-E Microfinance Bank",
    "eTranzact",
    "Evangel Microfinance Bank",
    "Evergreen Microfinance Bank",
    "EWT Microfinance Bank",
    "Excellent Microfinance Bank",
    "Eyowo",
    "FairMoney Microfinance Bank",
    "Fast Credit",
    "FAST Microfinance Bank",
    "FBN Mortgages Limited",
    "FBNMobile",
    "FBNQUEST Merchant Bank",
    "FCMB",
    "FCMB BETA",
    "FCMB Easy Account",
    "FCT Microfinance Bank",
    "Federal Polytechnic Nekede Microfinance Bank",
    "Federal University Dutse Microfinance Bank",
    "Fedeth Microfinance Bank",
    "FedPoly Nasarawa Microfinance Bank",
    "FET",
    "FEWCHORE FINANCE COMPANY LIMITED",
    "FFS Microfinance Bank",
    "FHA Mortgage Bank",
    "Fidelity Bank",
    "Fidelity Mobile",
    "Fidfund Microfinance Bank",
    "FIMS MFB",
    "FinaTrust Microfinance Bank",
    "Firmus Microfinance Bank",
    "First Apple Limited",
    "First Bank of Nigeria",
    "First Generation Mortgage Bank",
    "First Midas Microfinance Bank",
    "First Option Microfinance Bank",
    "First Royal Microfinance Bank",
    "Flourish MFB",
    "Flutterwave Technology Solutions Limited",
    "Fortis Microfinance Bank",
    "FortisMobile",
    "FSDH Merchant Bank",
    "Fullrange Microfinance Bank",
    "Fundquest Financial Services Limited",
    "Futo Microfinance Bank",
    "Gabsyn Microfinance Bank Limited",
    "Gashua Microfinance Bank",
    "Gateway Mortgage Bank",
    "Gbede Microfinance Bank",
    "Giant Stride Microfinance Bank",
    "Giginya Microfinance bank",
    "Girei Microfinance Bank",
    "Globus Bank",
    "Glory Microfinance Bank",
    "GMB Microfinance Bank",
    "GOLDMAN MFB",
    "GoMoney",
    "Good Neigbours Microfinance Bank",
    "Goodnews Microfinance Bank",
    "Gowans Microfinance Bank",
    "Green Energy Microfinance Bank",
    "GreenBank Microfinance Bank",
    "Greenville Microfinance Bank",
    "Greenwich Merchant Bank",
    "Grooming Microfinance Bank",
    "GTBank Plc",
    "GTI Microfinance Bank",
    "GTMobile",
    "Hackman Microfinance Bank",
    "Haggai Mortgage Bank Limited",
    "Halal Credit Microfinance Bank",
    "Hasal Microfinance Bank",
    "Headway Microfinance Bank",
    "Hedonmark",
    "Heritage",
    "HighStreet Microfinance Bank",
    "Homebase Mortgage Bank",
    "HopePSB",
    "IBA Microfinance Bank",
    "IBILE Microfinance Bank",
    "IBOLO Microfinance Bank",
    "Iboma Fadama Microfinance Bank",
    "Ibu-Aje Microfinance Bank",
    "Ijebu-Ife Microfinance Bank",
    "Ikenne Microfinance Bank",
    "Ikire Microfinance Bank",
    "Ikoyi-Osun Microfinance Bank",
    "Ilaro Poly Microfinance Bank",
    "Ilisan Microfinance Bank",
    "Imo State Microfinance Bank",
    "Imperial Homes Mortgage Bank",
    "Infinity Microfinance Bank",
    "Infinity Trust Mortgage Bank",
    "Innovectives Kesh",
    "Intellifin",
    "Interland Microfinance Bank",
    "Interswitch Limited",
    "IRL Microfinance Bank",
    "Isaleoyo Microfinance Bank",
    "Island Microfinance Bank",
    "Iwade MFB Ltd",
    "Iwoama Microfinance Bank",
    "Iyamoye Microfinance Bank",
    "Iyeru Okin Microfinance Bank",
    "Iyin Ekiti MFB",
    "JAIZ Bank",
    "Jessefield Microfinance Bank",
    "Jubilee-Life Mortgage Bank",
    "KadPoly Microfinance Bank",
    "Kayvee Microfinance Bank",
    "KC Microfinance Bank",
    "KCMB Microfinance Bank",
    "Kegow (Chamsmobile)",
    "Kenechukwu Microfinance Bank",
    "Keystone Bank",
    "Kontagora Microfinance Bank",
    "Kuda Microfinance Bank",
    "Lagos Building Investment Company",
    "Lapo Microfinance Bank",
    "Lavender Microfinance Bank",
    "Legend Microfinance Bank",
    "Lifegate Microfinance Bank",
    "Light MFB",
    "Lobrem Microfinance Bank",
    "Lotus Bank",
    "Lovonus Microfinance Bank",
    "M36",
    "MAB Allianz MFB",
    "Macrod MFB",
    "Mainland Microfinance Bank",
    "Mainstreet Microfinance Bank",
    "Maintrust Microfinance Bank",
    "Malachy Microfinance Bank",
    "Maritime Microfinance Bank",
    "MayFair Microfinance Bank",
    "MayFresh Mortgage Bank",
    "Medef Microfinance Bank",
    "Megapraise Microfinance Bank",
    "Mercury MFB",
    "Mgbidi Microfinance Bank",
    "Microbiz MFB",
    "Microcred Microfinance Bank",
    "Midland Microfinance Bank",
    "MintFinex Microfinance Bank",
    "Mkobo Microfinance Bank",
    "Mkudi",
    "Molusi Microfinance Bank",
    "MoMo PSB",
    "Money Trust Microfinance Bank",
    "MoneyBox",
    "MONIE POINT (Rolez Microfinance Bank)",
    "Moyofade Microfinance Bank",
    "Mutual Benefits Microfinance Bank",
    "Mutual Trust Microfinance Bank",
    "Nagarta Microfinance Bank",
    "Nassarawa Microfinance Bank",
    "Navy Microfinance Bank",
    "Ndiorah Microfinance Bank",
    "Neptune Microfinance Bank",
    "New Dawn Microfinance Bank",
    "New Golden Pastures Microfinance Bank",
    "New Prudential Bank",
    "Nigerian Prisons Microfinance Bank",
    "NIP Virtual Bank",
    "NIRSAL Microfinance Bank",
    "Nkpolu-Ust MFB",
    "Nnew Women Microfinance Bank",
    "Nova Merchant Bank",
    "NPF MicroFinance Bank",
    "Nsuk MFB",
    "Numo Microfinance Bank",
    "Nuture Microfinance Bank",
    "Nwannegadi Microfinance Bank",
    "OAU Microfinance Bank",
    "Oche Microfinance Bank",
    "Octopus Microfinance Bank",
    "Ohafia Microfinance Bank",
    "Ojokoro Microfinance Bank",
    "Oke-Aro Oredegbe Microfinance Bank",
    "Okpoga Microfinance Bank",
    "Okuku Microfinance Bank",
    "Olabisi Onabanjo University Microfinance Bank",
    "OLOFIN OWENA Microfinance Bank",
    "Olowolagba Microfinance Bank",
    "Oluchukwu Microfinance Bank",
    "Omiye Microfinance Bank",
    "Omoluabi savings and loans",
    "One Finance",
    "Opay Digital Services LTD",
    "Optimus Bank",
    "Oraukwu MFB",
    "Orisun MFB",
    "Orokam Microfinance Bank",
    "Oscotech Microfinance Bank",
    "Otech Microfinance Bank",
    "Otuo Microfinance Bank",
    "Paga",
    "Page Financials",
    "PalmPay Limited",
    "Parkway-ReadyCash",
    "Parralex Microfinance bank",
    "PatrickGold Microfinance Bank",
    "PayAttitude Online",
    "Paystack Payment Limited",
    "PecanTrust Microfinance Bank",
    "Pennywise Microfinance Bank",
    "Personal Trust Microfinance Bank",
    "Petra Microfinance Bank",
    "Pillar Microfinance Bank",
    "Platinum Mortgage Bank",
    "Polaris Bank",
    "Polybadan Microfinance Bank",
    "Polyunwana Microfinance Bank",
    "Preeminent Microfinance Bank",
    "Premium Trust Bank",
    "Prestige Microfinance Bank",
    "Pristine Divitis Microfinance Bank",
    "Projects Microfinance Bank",
    "Prophius",
    "Providus Bank",
    "Purplemoney Microfinance Bank",
    "Qube Microfinance Bank",
    "Quickfund Microfinance Bank",
    "Rand Merchant Bank",
    "Randalpha Microfinance Bank",
    "Rayyan MFB",
    "Refuge Mortgage Bank",
    "Regent Microfinance Bank",
    "Rehoboth Microfinance Bank",
    "Reliance Microfinance Bank",
    "RenMoney Microfinance Bank",
    "Rephidim Microfinance Bank",
    "Richway Microfinance Bank",
    "RIMA Growth Pathway Microfinance Bank",
    "Rockshield Microfinance Bank",
    "Royal Exchange Microfinance Bank",
    "Safe Haven Microfinance Bank",
    "SafeTrust",
    "Sagamu Microfinance Bank",
    "SageGrey Finance Limited",
    "SEAP Microfinance Bank",
    "Seed Capital Microfinance Bank",
    "Seedvest Microfinance Bank",
    "Shalom Microfinance Bank",
    "Shepherd Trust Microfinance Bank",
    "Shield Microfinance Bank",
    "Shongom Microfinance Bank",
    "Signature Bank",
    "SmartCash PSB",
    "Snow MFB",
    "Solid Allianze MFB",
    "Solidrock microfinance Bank",
    "Sparkle",
    "Stanbic IBTC @ease wallet",
    "StanbicIBTC Bank",
    "Standard Chartered",
    "Stanford Microfinance Bak",
    "Stateside Microfinance Bank",
    "Stellas Microfinance Bank",
    "Sterling Bank",
    "Sulspap Microfinance Bank",
    "Suntrust Bank",
    "Supreme Microfinance Bank",
    "TagPay",
    "Taj Bank",
    "Taj_Pinspay",
    "Tanadi Microfinance Bank",
    "Tasued Microfinance Bank",
    "TCF MFB",
    "Teamapt Limited",
    "TeasyMobile",
    "Tekla Finance Limited",
    "Think Finance Microfinance Bank",
    "Titan Trust Bank",
    "TitanPaystack",
    "Trident Microfinance Bank",
    "Trinity Financial Services Limited",
    "TripleA Microfinance Bank",
    "Trust Microfinance Bank",
    "Trustbond Mortgage Bank",
    "Trustfund Microfinance Bank",
    "U & C Microfinance Bank",
    "UDA Microfinance Bank",
    "Uhuru Microfinance Bank",
    "Ummah Microfinance Bank",
    "UNAAB Microfinance Bank",
    "Uniben Microfinance Bank",
    "Unical Microfinance Bank",
    "Unimaid Microfinance Bank",
    "Union Bank",
    "United Bank for Africa",
    "Unity Bank",
    "UniUyo Microfinance Bank",
    "UNN MFB",
    "Vas2nets Limited",
    "Verdant Microfinance Bank",
    "Verite Microfinance Bank",
    "VFD MFB",
    "Virtue Microfinance Bank",
    "Visa Microfinance Bank",
    "VTNetworks",
    "Waya Microfinance Bank",
    "Wema Bank",
    "Wetland Microfinance Bank",
    "Xslnce Microfinance Bank",
    "YCT Microfinance Bank",
    "Yes Microfinance Bank",
    "Yobe Microfinance Bank",
    "Zenith Bank Plc",
    "Zenith Eazy Wallet",
    "ZenithMobile",
    "Zikora Microfinance Bank",
    "Zinternet Nigera Limited",
    
    ]as const;
      
    export type BankName = string;